const env = require('dotenv');
env.config();

const { 
  MONGO_URI, 
  APP_PORT, 
  APP_NAME, 
  APP_BASE_URL, 
  APP_SERVICE_URL, 
  JWT_SECRET_KEY,
  JWT_REFRESH_TOKEN_SECRET_KEY,
  JWT_ACCESS_TOKEN_EXPIRES, 
  JWT_REFRESH_TOKEN_EXPIRES, 
  JWT_TOKEN_COOKIE_EXPIRES,
  SEND_SENDER_MAIL,
  SEND_GRID_API_KEY
} = process.env;

module.exports = {
  MONGO_URI, 
  APP_PORT, 
  APP_NAME, 
  APP_BASE_URL, 
  APP_SERVICE_URL, 
  JWT_SECRET_KEY,
  JWT_REFRESH_TOKEN_SECRET_KEY,
  JWT_ACCESS_TOKEN_EXPIRES, 
  JWT_REFRESH_TOKEN_EXPIRES, 
  JWT_TOKEN_COOKIE_EXPIRES,
  SEND_SENDER_MAIL,
  SEND_GRID_API_KEY
};
